"""log_project

Revision ID: 1f5fae402398
Revises: e430b9da5cdb
Create Date: 2025-05-15 13:12:10.638633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5fae402398'
down_revision: Union[str, None] = 'e430b9da5cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_logs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('project_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('project_logs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
