"""cascade

Revision ID: 435b0d248584
Revises: 1f5fae402398
Create Date: 2025-05-15 14:27:43.945451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435b0d248584'
down_revision: Union[str, None] = '1f5fae402398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('columns_project_id_fkey', 'columns', type_='foreignkey')
    op.create_foreign_key(None, 'columns', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_logs_user_id_fkey', 'project_logs', type_='foreignkey')
    op.drop_constraint('project_logs_task_id_fkey', 'project_logs', type_='foreignkey')
    op.drop_constraint('project_logs_project_id_fkey', 'project_logs', type_='foreignkey')
    op.create_foreign_key(None, 'project_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'project_logs', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_logs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_users_project_id_fkey', 'project_users', type_='foreignkey')
    op.create_foreign_key(None, 'project_users', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tasks_column_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_producer_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'columns', ['column_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['producer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key('tasks_producer_id_fkey', 'tasks', 'users', ['producer_id'], ['id'])
    op.create_foreign_key('tasks_column_id_fkey', 'tasks', 'columns', ['column_id'], ['id'])
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.create_foreign_key('project_users_project_id_fkey', 'project_users', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_logs', type_='foreignkey')
    op.drop_constraint(None, 'project_logs', type_='foreignkey')
    op.drop_constraint(None, 'project_logs', type_='foreignkey')
    op.create_foreign_key('project_logs_project_id_fkey', 'project_logs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_logs_task_id_fkey', 'project_logs', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('project_logs_user_id_fkey', 'project_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'columns', type_='foreignkey')
    op.create_foreign_key('columns_project_id_fkey', 'columns', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
