"""log_project_id

Revision ID: e430b9da5cdb
Revises: e6f52c3a2479
Create Date: 2025-05-15 12:15:34.923322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e430b9da5cdb'
down_revision: Union[str, None] = 'e6f52c3a2479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_logs', sa.Column('project_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'project_logs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_logs', type_='foreignkey')
    op.drop_column('project_logs', 'project_id')
    # ### end Alembic commands ###
